# Generated by Django 3.1.4 on 2020-12-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(verbose_name='Date creation')),
                ('update_date', models.DateTimeField(verbose_name='Date update')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=30)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(verbose_name='Date creation')),
                ('update_date', models.DateTimeField(verbose_name='Date update')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=30)),
            ],
        ),
    ]
